version: '3.8'

services:
  terraform:
    container_name: terraform
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${WORK_DIR}:/terraform
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-northeast-1}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}