version: '3.8'

services:
  terraform:
    container_name: terraform
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
    # /host/terraform/workdirを作業したいホスト側ディレクトリに修正してください
      - ../:/terraform
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}